apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-gnfnxdvk
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-gnfnxdvk:40357c9976922a204b8ad3766499a18e9ed8ed87@sha256:3040c92643c3d539246e27a4e72e14421635bdb2d6e8dbb55843ded3e17e7daf
          name: container-image
